### ISSUE TITLE
Taskband segfaults

### ISSUE THREAD

**Issue by rozniak** [rozniak/xfce-winxp-tc#306]
On Arch Linux (potentially other distros, unsure atm), the taskband seems liable to crashing, but it's not the same crash that I traced to GTK3 in #292 (Arch Linux is on 3.24.42 as of the time of writing).

**Comment by rozniak** [comment]
Reproducible by displaying a window that has no assigned icon, and no application ID set. (eg. open 'Printers and Faxes' from the Start menu, then close that window)

The crash appears to come from WNCK...
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/79735758-0a33-41b4-982c-a67f1148e61b)

However there is a fault in shelldpa when it attempts to read the icon name from the WM_CLASS attribute when the window is using a fallback icon. Not checking if WM_CLASS attrib is NULL before calling `gtk_icon_theme_load_icon`
![image](https://github.com/rozniak/xfce-winxp-tc/assets/13258281/c461597c-c523-49da-ae03-0d0cf28e51fa)

Will fix the latter issue, not sure if it will have any influence on the former but it still should be fixed.

**Comment by rozniak** [comment]
NTS: I have a sneaking suspicion this issue may be that the error dialog is blocking, so the calls to WNCK to retrieve the window data will run after the dialog is destroyed - will need to check this once I have time

**Comment by rozniak** [comment]
Doesn't appear to be a modal dialog issue, it's just when the GtkMessageDialog is closed regardless, WNCK crashes. It definitely seems like a WNCK bug but not sure why

**Comment by rozniak** [comment]
Identified the double whammy problem:
- If the window doesn't have a fallback icon we try to get the icon via the program name
- When this fails, the fallback icon is still used (though we hit a G_CRITICAL for trying to load NULL icon name)
- The way the logic is written atm is that the fallback icon doesn't get ref'd in the block that looks for the program name, so it gets destroyed early by us before WNCK

Will apply some fixes now, I guess this has just been working by pure chance on Debian. :weary:

**Comment by TheoCGaming** [comment]
still happening for me
archlinux kernel 6.10
aur package r322.150f0cb-1
not sure how to get it to produce logs

**Comment by TheoCGaming** [comment]
making a new issue (cause is completely different)
